# Generated by Django 5.1.15 on 2026-10-05 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loft',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
